# oc adm policy add-scc-to-user anyuid -z grafana

kind: ServiceAccount
apiVersion: v1
metadata:
  name: grafana
---
kind: Service
apiVersion: v1
metadata:
  name: grafana
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    name: grafana
---
kind: Route
apiVersion: v1
metadata:
  name: grafana
spec:
  host: yzamir-centos7-1.eng.lab.tlv.redhat.com
  path: /
  ports:
  - port: 3000
  tls:
    termination: edge
  to:
    kind: Service
    name: grafana
---
kind: DeploymentConfig
apiVersion: v1
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    name: grafana
  template:
    metadata:
      labels:
        name: grafana
    spec:
      containers:
      - name: grafana
        image: hawkular/hawkular-grafana-datasource
        ports:
        - containerPort: 3000
          protocol: TCP
      serviceAccountName: grafana
  expose: grafana
