apiVersion: v1
kind: Route
metadata:
  labels:
    metrics-infra: hawkular-metrics
    name: hawkular-metrics
  name: hawkular-metrics
spec:
  host: yzamir-centos7-2.eng.lab.tlv.redhat.com
  port:
    targetPort: https-endpoint
  to:
    kind: Service
    name: hawkular-metrics
  tls:
    termination: passthrough

